# 基础规则源
# 这个就是你要采用规则的源地址，会把代理填入这里面，然后把要覆盖的参数覆盖进去
base-config:
  #  - name: name
  #    url: url
  - name: normal
    url: "https://raw.githubusercontent.com/CrazyBunQnQ/SS-Rule-Snippet/baozi/LAZY_RULES/clash.yaml"
  - name: advanced
    url: "https://raw.githubusercontent.com/CrazyBunQnQ/SS-Rule-Snippet/baozi/LAZY_RULES/advanced.yaml"

# 不想要的节点 name, 支持正则表达式
filter-proxy-name:
#  - "名称 name"
  - "[港澳新]"
  - "[马柬鲜色哈英波瑞葡卢俄乌土廷巴南印德泰菲尼]"
  - "直连"
  - "套餐"

# 不想要的 节点 server, 支持正则表达式
filter-proxy-server:
#  - "server"

# 过滤的 proxy-providers
filter-proxy-providers:
#  - "server"
  - "provider1"
  - "test"

# 过滤的 proxy-groups
filter-proxy-groups:
#  - "server"
  - "UseProvider"
  - "relay"
  - "auto"
  - "fallback-auto"
  - "load-balance"
  - "Proxy"

# 拉取代理源
# 这个就是你的订阅地址，会从这个地址提取代理信息添加到上面的基础规则源里面

pull-proxy-source:
  #  按照下面的输入方式填写
  #  - name: name
  #    url: url
  - name: 闪电
    url: "https://update.cdn-sd.xyz/api/v1/client/subscribe?token=c57ea9414a9e803"
  - name: 魔戒
    url: "https://mojie.mx/api/v1/client/subscribe?token=7d3e8d95719649f"
  - name: 羊圈
    url: "https://mie-sub.pz.pe/subscribe/OOEPHV8?clash=ssr&trojan"


# 下面的参数都会覆盖或合并到最终生成的配置文件里面去

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Transparent proxy server port for Linux and macOS
# redir-port: 7892

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 允许局域网的连接（可用来共享代理）
allow-lan: true
bind-address: '*'
# 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
# "*"                           绑定所有的 IP 地址
# 192.168.122.11                绑定一个的 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]"   绑定一个 IPv6 地址

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent

# When set to false, resolver won't translate hostnames to IPv6 addresses ipv6 的支持
ipv6: false

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

# RESTful API 的口令 (可选)
secret: "123456"

# 出站网卡接口
# interface-name: en0

# DNS 服务器和建立连接时的 静态 Hosts, 仅在 dns.enhanced-mode 模式为 redir-host 生效
# 支持通配符域名 (例如: *.clash.dev, *.foo.*.example.com )
# 不使用通配符的域名优先级高于使用通配符的域名 (例如: foo.example.com > *.example.com > .example.com )
# 注意: +.foo.com 的效果等同于 .foo.com 和 foo.com
hosts:
# '*.clash.dev': 127.0.0.1
# '.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'

# DNS 服务器配置(可选；若不配置，程序内置的 DNS 服务会被关闭)
# dns:
#   enable: true
#   listen: 0.0.0.0:53
#   ipv6: true # 当此选项为 false 时, AAAA 请求将返回空
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true

#   # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
#   # 仅填写 DNS 服务器的 IP 地址
#   default-nameserver:
#     - 1.2.4.8
#     - 223.5.5.5
#     - 114.114.114.114
#     - 119.29.29.29
#     - 8.8.8.8
#   enhanced-mode: redir-host # 或 fake-ip
#   fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
#   # use-hosts: true # 查询 hosts 并返回 IP 记录
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true

#   # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
#   # fake-ip-filter:
#   #   - '*.lan'
#   #   - localhost.ptlogin2.qq.com

#   # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
#   # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
#   # Clash 会使用最先获得的解析记录回复 DNS 请求
#   nameserver:
#     - https://13800000000.rubyfish.cn/
#     - https://dns.alidns.com/dns-query
#     - https://doh.360.cn/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

#   # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
#   # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
#   # fallback:
#   #  - https://dns.google/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://8.8.4.4:853

#   # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
#   # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
#   #
#   # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
#   # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
#   #
#   # 当 fallback-filter.geoip 为 false, 如果解析结果在 fallback-filter.ipcidr 范围内，
#   # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
#   #
#   # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
#   fallback-filter:
#     geoip: true
#     ipcidr:
#     # - 240.0.0.0/4
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

proxies:
#  - name: "ss1"
#    type: ss
#    server: server
#    port: 443
#    cipher: chacha20-ietf-poly1305
#    password: "password"
#    # udp: true

proxy-groups:
#  # url-test 可以自动选择与指定 URL 测速后，延迟最短的服务器
#  - name: "auto"
#    type: url-test
#    url: 'http://www.gstatic.com/generate_204'
#    interval: 300

#  # fallback 可以尽量按照用户书写的服务器顺序，在确保服务器可用的情况下，自动选择服务器
#  - name: "fallback-auto"
#    type: fallback
#    url: 'http://www.gstatic.com/generate_204'
#    interval: 300
#
#  # load-balance 可以使相同 eTLD 请求在同一条代理线路上
#  - name: "load-balance"
#    type: load-balance
#    url: 'http://www.gstatic.com/generate_204'
#    interval: 300
  - name: "代理"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - 自动代理
  # url-test 可以自动代理与指定 URL 测速后，延迟最短的服务器
  - name: "自动代理"
    type: url-test
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 500
  - name: "电报消息"
    type: select
    proxies:
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "BiliBili"
    type: select
    proxies:
      - DIRECT
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
  - name: "YouTube"
    type: select
    proxies:
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "TikTok"
    type: select
    proxies:
      - 美国节点
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "Netflix"
    type: select
    proxies:
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "Disney+"
    type: select
    proxies:
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "Emby"
    type: select
    proxies:
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "隐私防护"
    type: select
    proxies:
      - REJECT
      - DIRECT
      - 代理
  - name: "游戏平台"
    type: select
    proxies:
      - DIRECT
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
  - name: "下载平台"
    type: select
    proxies:
      - DIRECT
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
  - name: "BT种子"
    type: select
    proxies:
      - DIRECT
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
  - name: "国内流量"
    type: select
    proxies:
      - DIRECT
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
  - name: "广告拦截"
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: "漏网之鱼"
    type: select
    proxies:
      - 代理
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "香港节点"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "日本节点"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "美国节点"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "台湾节点"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "新加坡节点"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "欧洲节点"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  - name: "社交平台IP归属地"
    type: select
    proxies:
      - DIRECT
      - 代理
  - name: "其他地区"
    type: select
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
      - DIRECT
  #  # fallback 可以尽量按照用户书写的服务器顺序，在确保服务器可用的情况下，自动选择服务器
  - name: "故障转移"
    type: fallback
    proxies:
      - 自动代理
      - http
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 500
  # 代理的转发链, 在 proxies 中不应该包含 relay. 不支持 UDP.
  # 流量: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> 互联网
  - name: "中继"
    type: relay
    proxies:
      - http
      - vmess
      - ss1
      - ss2
  # load-balance 可以使相同 eTLD 请求在同一条代理线路上
  - name: "负载均衡"
    type: load-balance
    proxies:
      - http
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 500

# 服务器节点订阅
proxy-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用
#   health-check: # 健康检查选项从此处开始
#     enable:
#     url:
#     interval:

#
# 「url」参数填写订阅链接
#
# 订阅链接可以使用 API 进行转换，如：https://sub.dler.io/
#
# 1.模式选择「进阶模式」 2.填写订阅链接 3.勾选「输出为 Node List」 4.「生成订阅链接」
#

rule-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   behavior: classical # 或 ipcidr、domain
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用
  IPfake:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml
    path: "./rule_provider/IPfake.yaml"
    interval: 259200
  BiliBili:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
    path: "./rule_provider/bilibili.yaml"
    interval: 259200
  Disney:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Disney/Disney.yaml
    path: "./rule_provider/Disney.yaml"
    interval: 259200
  Netflix:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Netflix/Netflix.yaml
    path: "./rule_provider/Netflix.yaml"
    interval: 259200
  TikTok:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/TikTok/TikTok.yaml
    path: "./rule_provider/TikTok.yaml"
    interval: 259200
  YouTube:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    path: "./rule_provider/YouTube.yaml"
    interval: 259200
  Telegram:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Telegram/Telegram.yaml
    path: "./rule_provider/Telegram.yaml"
    interval: 259200
  Emby:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/justdoiting/emby-rules/main/Emby.yaml
    path: "./rule_provider/Emby.yaml"
    interval: 259200
  Game:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Game/Game.yaml
    path: "./rule_provider/Game.yaml"
    interval: 259200
  BanEasyPrivacy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml
    path: "./rule_provider/BanEasyPrivacy.yaml"
    interval: 259200
  Advertising:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml
    path: "./rule_provider/Advertising.yaml"
    interval: 259200
  Download:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Download/Download.yaml
    path: "./rule_provider/Download.yaml"
    interval: 259200
  PrivateTracker:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml
    path: "./rule_provider/PrivateTracker.yaml"
    interval: 259200
  ChinaMax:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMaxNoIP/ChinaMaxNoIP_Classical.yaml
    path: "./rule_provider/ChinaMax.yaml"
    interval: 259200
  Global:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml
    path: "./rule_provider/Global.yaml"
    interval: 259200
  Lan:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Lan/Lan.yaml
    path: "./rule_provider/Lan.yaml"
    interval: 259200

rules:
  # 自定义规则
  ## 您可以在此处插入您补充的自定义规则（请注意保持缩进）
  # - DOMAIN,baidu.com,DIRECT # 域名 直连
  # - DOMAIN-SUFFIX,baidu.com,REJECT # 域名后缀 拒绝连接
  # - RULE-SET,BiliBili,BiliBili # 使用规则集
  # - DOMAIN-KEYWORD,bili,BiliBili # 域名关键词 使用指定组的连接配置
  # - IP-CIDR,127.0.0.0/8,DIRECT # IP段 直连
  - IP-CIDR,89.168.65.165/32,下载平台
  - IP-CIDR,195.154.184.151/32,下载平台
  #  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN,cdn-lfs.huggingface.co,DIRECT # 这个老六明明可以直连，却用梯子一下子干掉我 1T 流量...
  - DOMAIN,s.bingparachute.com,美国节点
  - DOMAIN,jcenter.bintray.com,DIRECT
  - DOMAIN-SUFFIX,t-msedge.net,DIRECT
  - DOMAIN-SUFFIX,openai.com,美国节点
  - DOMAIN-SUFFIX,bing.com,美国节点
  - DOMAIN-SUFFIX,monica.im,代理
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,ubits.club,下载平台
  - DOMAIN-SUFFIX,cloudfront.net,DIRECT
  - DOMAIN-SUFFIX,gradle.org,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,speedtest.net,DIRECT
  - DOMAIN-SUFFIX,intercom.io,美国节点
  - DOMAIN-SUFFIX,fakeopen.com,美国节点
  - DOMAIN-SUFFIX,kemono.party,代理
  - DOMAIN-SUFFIX,iwara.tv,代理
  - DOMAIN-SUFFIX,rule34video.com,代理
  - DOMAIN-SUFFIX,douban.com,DIRECT

  - DOMAIN-SUFFIX,gjfzpt.cn,REJECT
  - DOMAIN-KEYWORD,gmail,代理
  - DOMAIN-KEYWORD,google,代理
  - DOMAIN-SUFFIX,openai,美国节点
  - DOMAIN-SUFFIX,1e100.net,代理
  - DOMAIN-SUFFIX,2mdn.net,代理
  - DOMAIN-SUFFIX,app-measurement.net,代理
  - DOMAIN-SUFFIX,g.co,代理
  - DOMAIN-SUFFIX,ggpht.com,代理
  - DOMAIN-SUFFIX,goo.gl,代理
  - DOMAIN-SUFFIX,googleapis.cn,代理
  - DOMAIN-SUFFIX,googleapis.com,代理
  - DOMAIN-SUFFIX,gstatic.cn,代理
  - DOMAIN-SUFFIX,gstatic.com,代理
  - DOMAIN-SUFFIX,gvt0.com,代理
  - DOMAIN-SUFFIX,gvt1.com,代理
  - DOMAIN-SUFFIX,gvt2.com,代理
  - DOMAIN-SUFFIX,gvt3.com,代理
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,代理
  - DOMAIN-SUFFIX,youtu.be,代理
  - DOMAIN-SUFFIX,youtube-nocookie.com,代理
  - DOMAIN-SUFFIX,youtube.com,代理
  - DOMAIN-SUFFIX,yt.be,代理
  - DOMAIN-SUFFIX,ytimg.com,代理

  # - 规则集
  - RULE-SET,BiliBili,BiliBili
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney+
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Emby,Emby
  - RULE-SET,Telegram,电报消息
  - RULE-SET,Game,游戏平台
  - RULE-SET,BanEasyPrivacy,隐私防护
  - RULE-SET,Advertising,广告拦截
  - RULE-SET,Download,下载平台
  - RULE-SET,PrivateTracker,BT种子
  - RULE-SET,IPfake,社交平台IP归属地
  - RULE-SET,Lan,国内流量
  - RULE-SET,Global,代理
  - GEOIP,CN,DIRECT
  # - 其它
  - MATCH,漏网之鱼
